name: Generate Terraform Configuration

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS region for the S3 bucket'
        required: true
        default: 'us-west-2'
      bucket_name:
        description: 'Name for the S3 bucket'
        required: true
        default: 'my-example-bucket'
      folder_name:
        description: 'Unique folder name for resources'
        required: true
        default: 'default-folder'

jobs:
  create-terraform-file:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create unique folder for this run
        run: |
          export USER_FOLDER="./tf/${{ github.actor }}_${{ github.event.inputs.folder_name }}"
          mkdir -p "$USER_FOLDER"
          cp ./tf/main.tf "$USER_FOLDER"
          cp ./tf/variables.tf "$USER_FOLDER"  # Копируем файл переменных
          ls -al "$USER_FOLDER"  # Проверка содержимого папки для отладки

      - name: Update Terraform variables file
        run: |
          USER_FOLDER="./tf/${{ github.actor }}_${{ github.event.inputs.folder_name }}"
          echo "Updating variables file in $USER_FOLDER/variables.tf"
          
          # Проверка содержимого перед заменой
          echo "Current contents of variables.tf before updates:"
          cat "$USER_FOLDER/variables.tf"

          # Обновляем region
          if sed -i "s/default = \\".*\\"/default = \\"${{ github.event.inputs.region }}\\"/" "$USER_FOLDER/variables.tf"; then
            echo "Updated region successfully."
          else
            echo "Failed to update region."
          fi

          # Обновляем bucket_name
          if sed -i "s/default = \\".*\\"/default = \\"${{ github.event.inputs.bucket_name }}\\"/" "$USER_FOLDER/variables.tf"; then
            echo "Updated bucket_name successfully."
          else
            echo "Failed to update bucket_name."
          fi
          
          # Проверка изменений после замены
          echo "Updated contents of variables.tf after updates:"
          cat "$USER_FOLDER/variables.tf"


      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add "$USER_FOLDER/main.tf" "$USER_FOLDER/variables.tf"  # Коммитим оба файла
          git commit -m "Add Terraform configuration for $USER_FOLDER"
          git push
