name: Configure AWS Credentials

on:
  workflow_dispatch:

jobs:
  configure-aws:
    runs-on: ubuntu-latest

    steps:

      - name: Check Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAR5LYCFR7D2UDKGUK #${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: 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 #${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Verify AWS Credentials
        run: |
          aws s3 ls
