name: Deploy Resources via Terraform

on:
  repository_dispatch:
    types: [create-resource]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/YourRole
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="resource_type=${{ github.event.client_payload.resource_type }}" -var="resource_name=${{ github.event.client_payload.resource_name }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="resource_type=${{ github.event.client_payload.resource_type }}" -var="resource_name=${{ github.event.client_payload.resource_name }}"
