name: Deploy Resources via Terraform

on:
  repository_dispatch:
    types: [create-resource]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Variables
        run: |
          echo "Received Variables from Jira:"
          echo "Resource Type: ${{ github.event.client_payload.resource_type }}"
          echo "Resource Name: ${{ github.event.client_payload.resource_name }}"
