name: Share and Use Changed Directories

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

jobs:
  define-directories:
    runs-on: ubuntu-latest
    outputs:
      dirs: '["./tf5", "./tf1"]'  # Хардкодим директории
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for comparing commits

  use-directories:
    needs: define-directories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_path: ${{ fromJson(needs.define-directories.outputs.dirs) }}  # Преобразуем строку в массив
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run terraform plan for directories
        uses: dflook/terraform-plan@v1
        with:
          path: ${{ matrix.tf_path }}  # Применяем директорию из матрицы
          add_github_comment: "always-new"
